### ISSUE TITLE
can't run on WSL

### ISSUE THREAD

**Issue by fdncred** [rgwood/systemctl-tui#1]
It looks cool so I wanted to try it out on ubuntu wsl with systemd running. I get this
```
cargo r
Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/systemctl-tui`
Error: I/O error: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)
```
I assume that's because there's some file it's not able to find, or maybe it just doesn't work in WSL?

**Comment by rgwood** [comment]
Hmm, probably a WSL-specific issue; I haven’t tested it on WSL yet but it’s been fine on several native Linux machines.

**Comment by rgwood** [comment]
If you run the executable with sudo does it still fail?

**Comment by fdncred** [comment]
This could totally be my system too
```
> systemctl 
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by fdncred** [comment]
And yet, this works. Sorry for spamming you so much. WSL is a bit weird, but we know this already. :)
![image](https://github.com/rgwood/systemctl-tui/assets/343840/b3d0410f-9a72-43c5-8fc9-829f09fc3b90)

**Comment by fdncred** [comment]
One last spam. Here's the secret sauce for WSL. I added the `[boot]` section.
```toml
[interop]
enabled = true # enable launce of windows binaries; default is true
appendWindowsPath = false # append windows path to $PATH variable; default is true
systemd = true

[boot]
systemd = true

[network]
generateResolvConf = true
```

![image](https://github.com/rgwood/systemctl-tui/assets/343840/b7ea7df7-f326-4aa4-8aee-a3231be5b068)
